[package]
name = "rschema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rschema-core = { path = "rschema-core" }
rschema-derive = { path = "rschema-derive" }

[dev-dependencies]
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"

[[example]]
name = "config"
crate-type = ["staticlib"]

[[example]]
name = "generate"

[[example]]
name = "restore"
