[package]
name = "rschema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gen"
path = "src/bin/gen.rs"

[dependencies]
rschema-core = { path = "rschema-core" }
rschema-derive = { path = "rschema-derive" }