[package]
name = "json-schema-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gen"
path = "src/bin/gen.rs"

[dependencies]
json-schema-gen-core = { path = "json-schema-gen-core" }
json-schema-gen-derive = { path = "json-schema-gen-derive" }