prop_string: prop_string
prop_number_i8: 1
prop_number_i16: 2
prop_number_i32: 5
prop_number_i64: 10
prop_number_isize: 100
prop_number_u8: 1
prop_number_u16: 2
prop_number_u32: 5
prop_number_u64: 10
prop_number_usize: 100
prop_boolean: true
prop_optional: null
prop_single_type_array:
  - item1
  - item2
  - item3
prop_composite_type_array:
  - false
  - - 1
    - one
  - field: 999
    additional_property: true
prop_unit_struct: null
prop_empty_tuple_struct: []
prop_single_tuple_struct: single_tuple_struct
prop_tuple_struct:
  - 12
  - twelve
prop_empty_struct: {}
prop_struct:
  field_number: 123
  nested_struct:
    field_number: 987
prop_full_enum: true
prop_unit_variant_only_enum: Unit1
prop_required_prop: prop_required_prop
prop_required_prop2: prop_required_prop2